$axure.loadCurrentPage({
  "url":"product2.html",
  "generationDate":new Date(1420880725960.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"DroplistOption",
"ClickOnHandle"],
  "page":{
    "packageId":"e92e1d88e9b04f83894903afb674d7fd",
    "type":"Axure:Page",
    "name":"Product2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fe704e36bf024122a3b02b9115550fa3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"d925059089d7407aa612fa9c86535ac3"},
{
          "id":"a02fb74b033f4b93b35f628308d93288",
          "label":"sketchy box, medium",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":277},
            "size":{
              "width":306,
              "height":383},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da46154e1124407bb088abbd07496a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":277},
                "size":{
                  "width":306,
                  "height":383},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/sketchy_box__medium_u3.png"}},
{
          "id":"bd2de1c5297440eca9f2efe4f710a9a3",
          "label":"tab 1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":148,
              "y":260},
            "size":{
              "width":53,
              "height":21},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c5c9b874fe64427bfc3d20f34e64e7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":148,
                  "y":260},
                "size":{
                  "width":53,
                  "height":21},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"setFunction",
                      "description":"Set is selected of tab 1 equal to &quot;true&quot;, and<br> is selected of tab 2 equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bd2de1c5297440eca9f2efe4f710a9a3"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f635a10a34e3455ea0383d6a9b88cc5a"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/product2/tab_1_u5.png",
            "selected~":"images/product2/tab_1_u5_selected.png",
            "disabled~":"images/product2/tab_1_u5.png"}},
{
          "id":"86c9f8dcb86b445892c9010e5d97623c",
          "label":"tab 1 label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":149,
              "y":264},
            "size":{
              "width":49,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa9566f48ff0414898bc3e92b2e3c1b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":149,
                  "y":264},
                "size":{
                  "width":49,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"setFunction",
                      "description":"Set is selected of tab 1 equal to &quot;true&quot;, and<br> is selected of tab 2 equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bd2de1c5297440eca9f2efe4f710a9a3"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f635a10a34e3455ea0383d6a9b88cc5a"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f635a10a34e3455ea0383d6a9b88cc5a",
          "label":"tab 2",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":207,
              "y":260},
            "size":{
              "width":53,
              "height":21},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"738af1100f954c8c8ed77babfaf903cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":207,
                  "y":260},
                "size":{
                  "width":53,
                  "height":21},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"setFunction",
                      "description":"Set is selected of tab 1 equal to &quot;false&quot;, and<br> is selected of tab 2 equal to &quot;true&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bd2de1c5297440eca9f2efe4f710a9a3"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f635a10a34e3455ea0383d6a9b88cc5a"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/product2/tab_1_u5.png",
            "selected~":"images/product2/tab_1_u5_selected.png",
            "disabled~":"images/product2/tab_1_u5.png"}},
{
          "id":"e4e9d2c91e54489284f30809d1ad7788",
          "label":"tab 2 label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":209,
              "y":264},
            "size":{
              "width":49,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2387ea4451a94c068a44089dd704fedf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":209,
                  "y":264},
                "size":{
                  "width":49,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"setFunction",
                      "description":"Set is selected of tab 1 equal to &quot;false&quot;, and<br> is selected of tab 2 equal to &quot;true&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;, and<br> is selected of Unidentified equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bd2de1c5297440eca9f2efe4f710a9a3"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f635a10a34e3455ea0383d6a9b88cc5a"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"0f8c188a4c6b4e05b3001d06719bc4c7",
          "label":"box",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":434},
            "size":{
              "width":281,
              "height":143},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3af2ab08904f259f9856925b7ba4b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":434},
                "size":{
                  "width":281,
                  "height":143},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/box_u13.png"}},
{
          "id":"23f0f1d7ebbb42afae079e88d21cd103",
          "label":"line, diagonal L-R",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":434},
            "size":{
              "width":278,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb5e6cd7fbbc4142b8331ddec8213612",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":434},
                "size":{
                  "width":278,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
          "id":"e62edd8db40245f0b26f237b5021123e",
          "label":"line, diagonal R-L",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":434},
            "size":{
              "width":278,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87bd12dd29fd4f03b8a0d066311d424b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":434},
                "size":{
                  "width":278,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
          "id":"61358d0b582045e7a458ca2a66963989",
          "label":"image placement label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":251,
              "y":496},
            "size":{
              "width":76,
              "height":17},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"590165e89ef6425ba2bd971b82ef33b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":251,
                  "y":496},
                "size":{
                  "width":76,
                  "height":17},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/image_placement_label_u19.png"}},
{
          "id":"b241d398c26849a096f5d70d7815c6af",
          "label":"box",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":281},
            "size":{
              "width":281,
              "height":143},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1103e5cf10df47c3886cbeb9788560ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":281},
                "size":{
                  "width":281,
                  "height":143},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/box_u13.png"}},
{
          "id":"305d62baa424478487b9b39a2c7d6a57",
          "label":"line, diagonal L-R",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":281},
            "size":{
              "width":278,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"327320bb9e95482eb89fcca2394a85b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":281},
                "size":{
                  "width":278,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
          "id":"1b9447ad82a54b39bd49747593b8e82e",
          "label":"line, diagonal R-L",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":281},
            "size":{
              "width":278,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d080ec504f23443cb4683bff84bfbf29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":281},
                "size":{
                  "width":278,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
          "id":"417031ff660e40e5855800a31ddb9e9a",
          "label":"image placement label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":343},
            "size":{
              "width":76,
              "height":17},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca2bda87775b48c79fccaf6fb27aced2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":343},
                "size":{
                  "width":76,
                  "height":17},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/image_placement_label_u19.png"}},
{
          "id":"62ae4ba18b564f66a51915d9995d7fc0",
          "label":"box, transparent",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":132},
            "size":{
              "width":308,
              "height":122},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a99ee67c3af4e4cbbd04b2e26f7054e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":132},
                "size":{
                  "width":308,
                  "height":122},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/box__transparent_u29.png"}},
{
          "id":"9e769a602f434205b4f95c1b733f9f3c",
          "label":"tab",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":152,
              "y":132},
            "size":{
              "width":92,
              "height":14},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d260e0f79e54563a4f8dd71618368f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":152,
                  "y":132},
                "size":{
                  "width":92,
                  "height":14},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of tab equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9e769a602f434205b4f95c1b733f9f3c"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/product2/tab_u31.png",
            "selected~":"images/product2/tab_u31.png",
            "mouseDown~":"images/product2/tab_u31_mouseDown.png",
            "disabled~":"images/product2/tab_u31_disabled.png"}},
{
          "id":"1e8bf511901f4d288315cfbf9b73de21",
          "label":"tab label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":154,
              "y":135},
            "size":{
              "width":88,
              "height":11},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"878479f122724e1a85936ffb6e980a96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":154,
                  "y":135},
                "size":{
                  "width":88,
                  "height":11},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of tab equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9e769a602f434205b4f95c1b733f9f3c"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"709b450444d9421392c9d929cd9dd8d1",
          "label":"box",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":153},
            "size":{
              "width":90,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd98126369564ca6bd9fe47ce7753b40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":153},
                "size":{
                  "width":90,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/box_u35.png"}},
{
          "id":"b03a7cee353b472dbd856eebd7cfd238",
          "label":"line, diagonal L-R",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":153},
            "size":{
              "width":89,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"313fa19083df4a4cade664afd33765dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":153},
                "size":{
                  "width":89,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
          "id":"8872570203f345479c2eba3f288028ab",
          "label":"line, diagonal R-L",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":153},
            "size":{
              "width":89,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"996948f04941413289ace8a808198f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":153},
                "size":{
                  "width":89,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
          "id":"b5efb482d7c44536992ae902c580591e",
          "label":"image placement label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":193,
              "y":184},
            "size":{
              "width":24,
              "height":8},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fddb7077812f4d989a9edf8b0adf712a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":193,
                  "y":184},
                "size":{
                  "width":24,
                  "height":8},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/image_placement_label_u41.png"}},
{
          "id":"b5f83c4563b9494eb2738f23b3d8caf2",
          "label":"box",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":153},
            "size":{
              "width":90,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc9b432a732e4011be74fd3619c3dcb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":153},
                "size":{
                  "width":90,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/box_u35.png"}},
{
          "id":"7b08cf4d1fee42428bfd45ddabdd720a",
          "label":"line, diagonal L-R",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":153},
            "size":{
              "width":89,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"354684cd4a0744a990dce544c295a4eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":153},
                "size":{
                  "width":89,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
          "id":"2b3c4e2df63f476c9e83cd29185e15cb",
          "label":"line, diagonal R-L",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":153},
            "size":{
              "width":89,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36f1bd70243048f5ac0b5340d5d3dfe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":153},
                "size":{
                  "width":89,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
          "id":"1f068de859f24b91ac8ea0d89ff392b0",
          "label":"image placement label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":312,
              "y":184},
            "size":{
              "width":24,
              "height":8},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53474f60116148788478a4da68b5dd68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":312,
                  "y":184},
                "size":{
                  "width":24,
                  "height":8},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product2/image_placement_label_u41.png"}},
{
          "id":"ae95ae844ed34aed81f0ec85d7bb89f8",
          "label":"triangle, right",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
}},
            "location":{
              "x":398,
              "y":182},
            "size":{
              "width":32,
              "height":21},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d150863f7a704426a1d6eac30be562dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
}},
                "location":{
                  "x":398,
                  "y":182},
                "size":{
                  "width":32,
                  "height":21},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of triangle, right equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ae95ae844ed34aed81f0ec85d7bb89f8"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/product2/triangle__right_u51.png",
            "selected~":"images/product2/triangle__right_u51_selected.png"}},
{
          "id":"b7d346e81ff9443f9f4dd8b491b6dbb2",
          "label":"tab",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":270,
              "y":260},
            "size":{
              "width":91,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a07403b5d24c4f9ba2f9ef453ab7547c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":270,
                  "y":260},
                "size":{
                  "width":91,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of tab equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b7d346e81ff9443f9f4dd8b491b6dbb2"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/销售单管理/tab_u67.png",
            "selected~":"images/销售单管理/tab_u67_selected.png",
            "mouseDown~":"images/销售单管理/tab_u67_mouseDown.png",
            "disabled~":"images/销售单管理/tab_u67.png"}},
{
          "id":"5db996e3fdfe46e9a0dee256596d3ca2",
          "label":"tab label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":274,
              "y":264},
            "size":{
              "width":83,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124875d17d984334be20933261dd972a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":274,
                  "y":264},
                "size":{
                  "width":83,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of tab equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b7d346e81ff9443f9f4dd8b491b6dbb2"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d925059089d7407aa612fa9c86535ac3":{
      "packageId":"d925059089d7407aa612fa9c86535ac3",
      "type":"Axure:Master",
      "name":"Group",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bb956eace71741d39ff8d1d233d848a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":110,
                "y":19},
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"34e7f17d8003487ea75777fee257eebd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":110,
                    "y":19},
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/group/u1.png"}}]}}},
  "objectPaths":{
    "fe704e36bf024122a3b02b9115550fa3":{
      "scriptId":"u0",
      "bb956eace71741d39ff8d1d233d848a6":{
        "scriptId":"u1"},
      "34e7f17d8003487ea75777fee257eebd":{
        "scriptId":"u2"}},
    "a02fb74b033f4b93b35f628308d93288":{
      "scriptId":"u3"},
    "da46154e1124407bb088abbd07496a9f":{
      "scriptId":"u4"},
    "bd2de1c5297440eca9f2efe4f710a9a3":{
      "scriptId":"u5"},
    "5c5c9b874fe64427bfc3d20f34e64e7d":{
      "scriptId":"u6"},
    "86c9f8dcb86b445892c9010e5d97623c":{
      "scriptId":"u7"},
    "aa9566f48ff0414898bc3e92b2e3c1b4":{
      "scriptId":"u8"},
    "f635a10a34e3455ea0383d6a9b88cc5a":{
      "scriptId":"u9"},
    "738af1100f954c8c8ed77babfaf903cc":{
      "scriptId":"u10"},
    "e4e9d2c91e54489284f30809d1ad7788":{
      "scriptId":"u11"},
    "2387ea4451a94c068a44089dd704fedf":{
      "scriptId":"u12"},
    "0f8c188a4c6b4e05b3001d06719bc4c7":{
      "scriptId":"u13"},
    "3e3af2ab08904f259f9856925b7ba4b0":{
      "scriptId":"u14"},
    "23f0f1d7ebbb42afae079e88d21cd103":{
      "scriptId":"u15"},
    "fb5e6cd7fbbc4142b8331ddec8213612":{
      "scriptId":"u16"},
    "e62edd8db40245f0b26f237b5021123e":{
      "scriptId":"u17"},
    "87bd12dd29fd4f03b8a0d066311d424b":{
      "scriptId":"u18"},
    "61358d0b582045e7a458ca2a66963989":{
      "scriptId":"u19"},
    "590165e89ef6425ba2bd971b82ef33b5":{
      "scriptId":"u20"},
    "b241d398c26849a096f5d70d7815c6af":{
      "scriptId":"u21"},
    "1103e5cf10df47c3886cbeb9788560ef":{
      "scriptId":"u22"},
    "305d62baa424478487b9b39a2c7d6a57":{
      "scriptId":"u23"},
    "327320bb9e95482eb89fcca2394a85b6":{
      "scriptId":"u24"},
    "1b9447ad82a54b39bd49747593b8e82e":{
      "scriptId":"u25"},
    "d080ec504f23443cb4683bff84bfbf29":{
      "scriptId":"u26"},
    "417031ff660e40e5855800a31ddb9e9a":{
      "scriptId":"u27"},
    "ca2bda87775b48c79fccaf6fb27aced2":{
      "scriptId":"u28"},
    "62ae4ba18b564f66a51915d9995d7fc0":{
      "scriptId":"u29"},
    "7a99ee67c3af4e4cbbd04b2e26f7054e":{
      "scriptId":"u30"},
    "9e769a602f434205b4f95c1b733f9f3c":{
      "scriptId":"u31"},
    "8d260e0f79e54563a4f8dd71618368f4":{
      "scriptId":"u32"},
    "1e8bf511901f4d288315cfbf9b73de21":{
      "scriptId":"u33"},
    "878479f122724e1a85936ffb6e980a96":{
      "scriptId":"u34"},
    "709b450444d9421392c9d929cd9dd8d1":{
      "scriptId":"u35"},
    "fd98126369564ca6bd9fe47ce7753b40":{
      "scriptId":"u36"},
    "b03a7cee353b472dbd856eebd7cfd238":{
      "scriptId":"u37"},
    "313fa19083df4a4cade664afd33765dd":{
      "scriptId":"u38"},
    "8872570203f345479c2eba3f288028ab":{
      "scriptId":"u39"},
    "996948f04941413289ace8a808198f53":{
      "scriptId":"u40"},
    "b5efb482d7c44536992ae902c580591e":{
      "scriptId":"u41"},
    "fddb7077812f4d989a9edf8b0adf712a":{
      "scriptId":"u42"},
    "b5f83c4563b9494eb2738f23b3d8caf2":{
      "scriptId":"u43"},
    "cc9b432a732e4011be74fd3619c3dcb1":{
      "scriptId":"u44"},
    "7b08cf4d1fee42428bfd45ddabdd720a":{
      "scriptId":"u45"},
    "354684cd4a0744a990dce544c295a4eb":{
      "scriptId":"u46"},
    "2b3c4e2df63f476c9e83cd29185e15cb":{
      "scriptId":"u47"},
    "36f1bd70243048f5ac0b5340d5d3dfe9":{
      "scriptId":"u48"},
    "1f068de859f24b91ac8ea0d89ff392b0":{
      "scriptId":"u49"},
    "53474f60116148788478a4da68b5dd68":{
      "scriptId":"u50"},
    "ae95ae844ed34aed81f0ec85d7bb89f8":{
      "scriptId":"u51"},
    "d150863f7a704426a1d6eac30be562dc":{
      "scriptId":"u52"},
    "b7d346e81ff9443f9f4dd8b491b6dbb2":{
      "scriptId":"u53"},
    "a07403b5d24c4f9ba2f9ef453ab7547c":{
      "scriptId":"u54"},
    "5db996e3fdfe46e9a0dee256596d3ca2":{
      "scriptId":"u55"},
    "124875d17d984334be20933261dd972a":{
      "scriptId":"u56"}}});