$axure.loadCurrentPage({
  "url":"份子钱明细.html",
  "generationDate":new Date(1422084560428.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"DroplistOption",
"ClickOnHandle"],
  "page":{
    "packageId":"7336230f5c0c47b9aa705b176c43430c",
    "type":"Axure:Page",
    "name":"份子钱明细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c03e5cc1d42547f685d113b156ac778c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d925059089d7407aa612fa9c86535ac3"},
{
          "id":"5ecd5235f8834b358752da479f3224a4",
          "label":"box, transparent",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":150,
              "y":150},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"988f5700a59e496bb45c3e6a4fdda8fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":150,
                  "y":150},
                "size":{
                  "width":300,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/份子钱明细/box__transparent_u3.png"}},
{
          "id":"ef587064a3ac43a38b613b33585b71c7",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":160},
            "size":{
              "width":220,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5860737baf442a4a085ec6932cf3799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":160},
                "size":{
                  "width":220,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ef4568a7c4044aba29d7c44f232a0e6",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":185},
            "size":{
              "width":300,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"816220b29b8149e5b024eca7da36fa1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":185},
                "size":{
                  "width":300,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b8f409291504f4db96494456f8dafb9",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":210},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b235d833ab334dd9ac2b74ec21217b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":210},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"499442e0d23f41a090c0b66082e324f6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":260},
            "size":{
              "width":10,
              "height":410}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/份子钱明细/u11_line.png"}},
{
          "id":"58103ed7213e440d88c46f33f2abd20f",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":260},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1293e8586ef6423b97690e5fd4e47e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":260},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2bb37d90b543d6a3a5e5bc2ffc9f80",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":280,
              "y":260},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"973ce2450e1b4c1197e778b1162c6b3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":280,
                  "y":260},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e276e4937e94492b059490b7f43aacb",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":320},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"418dc91e28fa483481d2e9438587a91a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":320},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb0a7147a516425592f3bfd34cda006a",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":309,
              "y":310},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bea92ecef9514a929559a14ef2124d89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":309,
                  "y":310},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"792bb92522de4a0e82a7de621424db67",
          "label":"box",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":310},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a230de9ffe542b098b6a08dd837b641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":310},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/份子钱明细/box_u20.png"}},
{
          "id":"55d7c286731f437ebefb22e310ce4cd8",
          "label":"line, diagonal L-R",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":310},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b18c440bd9f048fcb33087fd4830968d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":310},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
          "id":"1bea79c2be0f4249a10ade32d00f71db",
          "label":"line, diagonal R-L",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":310},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19b1d66e40a14c178a4d5a5af070b457",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":310},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
          "id":"0e156da7fb8a490482b273f70ce82f97",
          "label":"image placement label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":268,
              "y":332},
            "size":{
              "width":13,
              "height":6},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b57817d785b4cca867b120c15fee9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":268,
                  "y":332},
                "size":{
                  "width":13,
                  "height":6},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/份子钱明细/image_placement_label_u26.png"}},
{
          "id":"613bef99da5d44a688d7ee38433fc805",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":309,
              "y":335},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4522ca24c41141aca778f9a294b7b80b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":309,
                  "y":335},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2ebd9aeacdc47609fed1f06e55487d0",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":387},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af67faa8251248d98af1fa8a2d8b1f1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":387},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b4d246583bb4e228fd21545415e1568",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":309,
              "y":377},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8950b722bd8d47a4a6d4bc0f7c81d556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":309,
                  "y":377},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"946d019ab37d4549a79c3aa338ac14fc",
          "label":"box",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":377},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fcb2b283f96475da903e9fe5d98b881",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":377},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/份子钱明细/box_u20.png"}},
{
          "id":"fbd273522e9343a1a46affdaa762bb02",
          "label":"line, diagonal L-R",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":377},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66414615e7c94e499b9a5d0cf1686576",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":377},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
          "id":"e0f578040d7c40feb11d6c3301c47f57",
          "label":"line, diagonal R-L",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":377},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c28d99e1c1b043debb90c56dd04ec4a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":377},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
          "id":"d03799cdd41b45e8940ed050dd8c1627",
          "label":"image placement label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":268,
              "y":399},
            "size":{
              "width":13,
              "height":6},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"508ceba28c9f4d369fca2303a39d78ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":268,
                  "y":399},
                "size":{
                  "width":13,
                  "height":6},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/份子钱明细/image_placement_label_u26.png"}},
{
          "id":"15bf055966eb4d8997c55a652da1b377",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":309,
              "y":402},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18d7e7af22c84cf09df51c59d7de3542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":309,
                  "y":402},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6837ca9277964bb6951fc7d8a3ccd571",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":380,
              "y":467},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109792ea5c984c31868aca6f236bfd44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":380,
                  "y":467},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ed4a0d9fe0441c891708176ce67790c",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":309,
              "y":467},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d3294f0a494bb6bb447e21d50f0212",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":309,
                  "y":467},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5b8f9a1602f4056a81e417023f649e5",
          "label":"box",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":467},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed6a36295ee466ab6e5b71c0afaea4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":467},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/份子钱明细/box_u20.png"}},
{
          "id":"56dff3b9809249d2ba273a70da9349d0",
          "label":"line, diagonal L-R",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":467},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"635fe50990e84ea984d99082a1afd998",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":467},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
          "id":"1aac1aadabc341c39625a0ea4039f23a",
          "label":"line, diagonal R-L",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":467},
            "size":{
              "width":49,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b96d25fbcaf407cba248b03bef41a4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":467},
                "size":{
                  "width":49,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
          "id":"2a32263c43d143f9adc2051b7d365460",
          "label":"image placement label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":268,
              "y":489},
            "size":{
              "width":13,
              "height":6},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"103d4ae56aac481da24f5aa64aa326ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":268,
                  "y":489},
                "size":{
                  "width":13,
                  "height":6},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/份子钱明细/image_placement_label_u26.png"}},
{
          "id":"7412fa6477564614875fa547ae550320",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":309,
              "y":492},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"195c1219733149f2a3411b171cc94b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":309,
                  "y":492},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d5b7f887f8a4bcf93383a66dd681fbc",
          "label":"button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":222.5,
              "y":670},
            "size":{
              "width":104,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97cf493e499e4ea6a14c412cb86ac40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":222.5,
                  "y":670},
                "size":{
                  "width":104,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9d5b7f887f8a4bcf93383a66dd681fbc"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9d5b7f887f8a4bcf93383a66dd681fbc"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/销售单管理/button_u53.png",
            "selected~":"images/销售单管理/button_u53_selected.png",
            "mouseOver~":"images/销售单管理/button_u53_selected.png",
            "mouseDown~":"images/销售单管理/button_u53_mouseDown.png",
            "disabled~":"images/销售单管理/button_u53_disabled.png"}},
{
          "id":"70b756f77f874dbaa28341fd0a7b49d3",
          "label":"button label",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":222,
              "y":674},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a36326dac02744ed9fb6096d2a8812de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":222,
                  "y":674},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9d5b7f887f8a4bcf93383a66dd681fbc"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9d5b7f887f8a4bcf93383a66dd681fbc"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d925059089d7407aa612fa9c86535ac3":{
      "packageId":"d925059089d7407aa612fa9c86535ac3",
      "type":"Axure:Master",
      "name":"Group",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bb956eace71741d39ff8d1d233d848a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":110,
                "y":19},
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"34e7f17d8003487ea75777fee257eebd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":110,
                    "y":19},
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/group/u1.png"}}]}}},
  "objectPaths":{
    "c03e5cc1d42547f685d113b156ac778c":{
      "scriptId":"u0",
      "bb956eace71741d39ff8d1d233d848a6":{
        "scriptId":"u1"},
      "34e7f17d8003487ea75777fee257eebd":{
        "scriptId":"u2"}},
    "5ecd5235f8834b358752da479f3224a4":{
      "scriptId":"u3"},
    "988f5700a59e496bb45c3e6a4fdda8fd":{
      "scriptId":"u4"},
    "ef587064a3ac43a38b613b33585b71c7":{
      "scriptId":"u5"},
    "d5860737baf442a4a085ec6932cf3799":{
      "scriptId":"u6"},
    "7ef4568a7c4044aba29d7c44f232a0e6":{
      "scriptId":"u7"},
    "816220b29b8149e5b024eca7da36fa1c":{
      "scriptId":"u8"},
    "7b8f409291504f4db96494456f8dafb9":{
      "scriptId":"u9"},
    "b235d833ab334dd9ac2b74ec21217b3a":{
      "scriptId":"u10"},
    "499442e0d23f41a090c0b66082e324f6":{
      "scriptId":"u11"},
    "58103ed7213e440d88c46f33f2abd20f":{
      "scriptId":"u12"},
    "1293e8586ef6423b97690e5fd4e47e39":{
      "scriptId":"u13"},
    "4d2bb37d90b543d6a3a5e5bc2ffc9f80":{
      "scriptId":"u14"},
    "973ce2450e1b4c1197e778b1162c6b3c":{
      "scriptId":"u15"},
    "8e276e4937e94492b059490b7f43aacb":{
      "scriptId":"u16"},
    "418dc91e28fa483481d2e9438587a91a":{
      "scriptId":"u17"},
    "bb0a7147a516425592f3bfd34cda006a":{
      "scriptId":"u18"},
    "bea92ecef9514a929559a14ef2124d89":{
      "scriptId":"u19"},
    "792bb92522de4a0e82a7de621424db67":{
      "scriptId":"u20"},
    "6a230de9ffe542b098b6a08dd837b641":{
      "scriptId":"u21"},
    "55d7c286731f437ebefb22e310ce4cd8":{
      "scriptId":"u22"},
    "b18c440bd9f048fcb33087fd4830968d":{
      "scriptId":"u23"},
    "1bea79c2be0f4249a10ade32d00f71db":{
      "scriptId":"u24"},
    "19b1d66e40a14c178a4d5a5af070b457":{
      "scriptId":"u25"},
    "0e156da7fb8a490482b273f70ce82f97":{
      "scriptId":"u26"},
    "4b57817d785b4cca867b120c15fee9ef":{
      "scriptId":"u27"},
    "613bef99da5d44a688d7ee38433fc805":{
      "scriptId":"u28"},
    "4522ca24c41141aca778f9a294b7b80b":{
      "scriptId":"u29"},
    "d2ebd9aeacdc47609fed1f06e55487d0":{
      "scriptId":"u30"},
    "af67faa8251248d98af1fa8a2d8b1f1f":{
      "scriptId":"u31"},
    "5b4d246583bb4e228fd21545415e1568":{
      "scriptId":"u32"},
    "8950b722bd8d47a4a6d4bc0f7c81d556":{
      "scriptId":"u33"},
    "946d019ab37d4549a79c3aa338ac14fc":{
      "scriptId":"u34"},
    "9fcb2b283f96475da903e9fe5d98b881":{
      "scriptId":"u35"},
    "fbd273522e9343a1a46affdaa762bb02":{
      "scriptId":"u36"},
    "66414615e7c94e499b9a5d0cf1686576":{
      "scriptId":"u37"},
    "e0f578040d7c40feb11d6c3301c47f57":{
      "scriptId":"u38"},
    "c28d99e1c1b043debb90c56dd04ec4a5":{
      "scriptId":"u39"},
    "d03799cdd41b45e8940ed050dd8c1627":{
      "scriptId":"u40"},
    "508ceba28c9f4d369fca2303a39d78ba":{
      "scriptId":"u41"},
    "15bf055966eb4d8997c55a652da1b377":{
      "scriptId":"u42"},
    "18d7e7af22c84cf09df51c59d7de3542":{
      "scriptId":"u43"},
    "6837ca9277964bb6951fc7d8a3ccd571":{
      "scriptId":"u44"},
    "109792ea5c984c31868aca6f236bfd44":{
      "scriptId":"u45"},
    "8ed4a0d9fe0441c891708176ce67790c":{
      "scriptId":"u46"},
    "53d3294f0a494bb6bb447e21d50f0212":{
      "scriptId":"u47"},
    "e5b8f9a1602f4056a81e417023f649e5":{
      "scriptId":"u48"},
    "7ed6a36295ee466ab6e5b71c0afaea4c":{
      "scriptId":"u49"},
    "56dff3b9809249d2ba273a70da9349d0":{
      "scriptId":"u50"},
    "635fe50990e84ea984d99082a1afd998":{
      "scriptId":"u51"},
    "1aac1aadabc341c39625a0ea4039f23a":{
      "scriptId":"u52"},
    "9b96d25fbcaf407cba248b03bef41a4b":{
      "scriptId":"u53"},
    "2a32263c43d143f9adc2051b7d365460":{
      "scriptId":"u54"},
    "103d4ae56aac481da24f5aa64aa326ce":{
      "scriptId":"u55"},
    "7412fa6477564614875fa547ae550320":{
      "scriptId":"u56"},
    "195c1219733149f2a3411b171cc94b01":{
      "scriptId":"u57"},
    "9d5b7f887f8a4bcf93383a66dd681fbc":{
      "scriptId":"u58"},
    "97cf493e499e4ea6a14c412cb86ac40d":{
      "scriptId":"u59"},
    "70b756f77f874dbaa28341fd0a7b49d3":{
      "scriptId":"u60"},
    "a36326dac02744ed9fb6096d2a8812de":{
      "scriptId":"u61"}}});