$axure.loadCurrentPage({
  "url":"orderdetail.html",
  "generationDate":new Date(1421046072813.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"DroplistOption",
"ClickOnHandle"],
  "page":{
    "packageId":"983b014e20a846df80d8c17a9f577310",
    "type":"Axure:Page",
    "name":"OrderDetail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7b20563470664ef98577aec7bd2155e9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d925059089d7407aa612fa9c86535ac3"},
{
          "id":"9c66b5f0d15b485cba56506cfd4f7f93",
          "label":"box, transparent",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":146,
              "y":143},
            "size":{
              "width":314,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34042213e26b434eafa9b1485b61a37f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":146,
                  "y":143},
                "size":{
                  "width":314,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orderdetail/box__transparent_u3.png"}},
{
          "id":"5492d37b90264b3581afbdfcdd8b49a1",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":150},
            "size":{
              "width":160,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5de589ff82346c1ac79b8dbc9915a06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":150},
                "size":{
                  "width":160,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97a4943f5d224c5f90d49a62defc3d06",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":175},
            "size":{
              "width":160,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f51c721fbd934143b7a92807191628bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":175},
                "size":{
                  "width":160,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6890bb4a373486c805f3b7751385487",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":200},
            "size":{
              "width":220,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0483ab1930844ac9e26151a629ec506",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":200},
                "size":{
                  "width":220,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da73ca0465aa43c5ab910173213cba80",
          "label":"box, transparent",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":146,
              "y":250},
            "size":{
              "width":314,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e08f803eca4149488e1be53e099695e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":146,
                  "y":250},
                "size":{
                  "width":314,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orderdetail/box__transparent_u11.png"}},
{
          "id":"071a15f3eb6445c09cd3d45dadd010c1",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":265},
            "size":{
              "width":240,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62c4d7fbe91549d4b41e4f75cbb12644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":265},
                "size":{
                  "width":240,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0430879f22474fc387b734bb9c814693",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":290},
            "size":{
              "width":160,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f413b53cafd1472c899099fd56a6a85e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":290},
                "size":{
                  "width":160,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c9ff36143ee4cf69bacbf1729d573f5",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":330,
              "y":265},
            "size":{
              "width":110,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e82fe01e3c492b965071efed8e7029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":330,
                  "y":265},
                "size":{
                  "width":110,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0eba0dbe7af24b7b927f6cb876c9ed42",
          "label":"box, transparent",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":146,
              "y":340},
            "size":{
              "width":314,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66d1773fc2a64909b55659fe6ca637f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":146,
                  "y":340},
                "size":{
                  "width":314,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orderdetail/box__transparent_u19.png"}},
{
          "id":"5bc64df110db4dfca0e26c9336b4a3f3",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":355},
            "size":{
              "width":260,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08f2702e4d764daa9d77a41c42c46feb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":355},
                "size":{
                  "width":260,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7753204f9533438ab79d8326bce18a10",
          "label":"box",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":160,
              "y":380},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c73ed1b6bfb245b888379335bfa108f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":160,
                  "y":380},
                "size":{
                  "width":90,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orderdetail/box_u23.png"}},
{
          "id":"39e8171fa5a2417495d1233555cba15e",
          "label":"line, diagonal L-R",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":160,
              "y":380},
            "size":{
              "width":89,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a30c1f8376e46b983c203e13d9cc19c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":160,
                  "y":380},
                "size":{
                  "width":89,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
          "id":"2298954c4b8a4eebb5a05eeb7e4f9d2b",
          "label":"line, diagonal R-L",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":160,
              "y":380},
            "size":{
              "width":89,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52dc7bf74fec422299681336bcc56f2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":160,
                  "y":380},
                "size":{
                  "width":89,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
          "id":"314f3d8d4d204881990642cfca46cdfa",
          "label":"image placement label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":192,
              "y":402},
            "size":{
              "width":24,
              "height":6},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c760e10abbd4e81a590b7286f40ddb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":192,
                  "y":402},
                "size":{
                  "width":24,
                  "height":6},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orderdetail/image_placement_label_u29.png"}},
{
          "id":"8d3a1ea43ede4bfc9ffdc37ee6f09700",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":259,
              "y":376},
            "size":{
              "width":110,
              "height":54},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cde21dbd3c8940e4a82c117649ce65ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":259,
                  "y":376},
                "size":{
                  "width":110,
                  "height":54},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b16a62c169a4240aa9fc70911fa5432",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":360,
              "y":370},
            "size":{
              "width":70,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c92df91fc87c45639c4dca904a3a52e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":360,
                  "y":370},
                "size":{
                  "width":70,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c1bcea9859423cb512858d4225c680",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":170,
              "y":455},
            "size":{
              "width":260,
              "height":55},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32544cdbafaf47e89896fd7b45e134fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":170,
                  "y":455},
                "size":{
                  "width":260,
                  "height":55},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0b831aa3469473c92e5b333ff564a39",
          "label":"button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":160,
              "y":660},
            "size":{
              "width":104,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6a200a33e7d497f8dcece2615d65f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":160,
                  "y":660},
                "size":{
                  "width":104,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b0b831aa3469473c92e5b333ff564a39"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b0b831aa3469473c92e5b333ff564a39"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/销售单管理/button_u53.png",
            "selected~":"images/销售单管理/button_u53_selected.png",
            "mouseOver~":"images/销售单管理/button_u53_selected.png",
            "mouseDown~":"images/销售单管理/button_u53_mouseDown.png",
            "disabled~":"images/销售单管理/button_u53_disabled.png"}},
{
          "id":"3cc748e0aff7474694b3d47089f1d225",
          "label":"button label",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":160,
              "y":664},
            "size":{
              "width":56,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f406a4931b4f2c94bce56c486f2256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":160,
                  "y":664},
                "size":{
                  "width":56,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b0b831aa3469473c92e5b333ff564a39"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b0b831aa3469473c92e5b333ff564a39"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaef942887f544998fffb280d16e004a",
          "label":"button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":270,
              "y":660},
            "size":{
              "width":104,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0070613b3f7d48a284dfe5de4924a3a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":270,
                  "y":660},
                "size":{
                  "width":104,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["eaef942887f544998fffb280d16e004a"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["eaef942887f544998fffb280d16e004a"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/销售单管理/button_u53.png",
            "selected~":"images/销售单管理/button_u53_selected.png",
            "mouseOver~":"images/销售单管理/button_u53_selected.png",
            "mouseDown~":"images/销售单管理/button_u53_mouseDown.png",
            "disabled~":"images/销售单管理/button_u53_disabled.png"}},
{
          "id":"fff1ecb4a2894cbab8d2eaa53b9e068c",
          "label":"button label",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":259,
              "y":663},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1c0611e8b494855a0b242426c4d6eb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":259,
                  "y":663},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["eaef942887f544998fffb280d16e004a"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["eaef942887f544998fffb280d16e004a"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"315e45a1d2a64a42871741f3a4e14770",
          "label":"button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":384,
              "y":658},
            "size":{
              "width":104,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b189fb362284fadaaa014372a5ebe6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":384,
                  "y":658},
                "size":{
                  "width":104,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["315e45a1d2a64a42871741f3a4e14770"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["315e45a1d2a64a42871741f3a4e14770"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/销售单管理/button_u53.png",
            "selected~":"images/销售单管理/button_u53_selected.png",
            "mouseOver~":"images/销售单管理/button_u53_selected.png",
            "mouseDown~":"images/销售单管理/button_u53_mouseDown.png",
            "disabled~":"images/销售单管理/button_u53_disabled.png"}},
{
          "id":"f8924feb57c648028ff071bd75d0c4fa",
          "label":"button label",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":369,
              "y":661},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da9c9383e421418d9d208336b12a054e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":369,
                  "y":661},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["315e45a1d2a64a42871741f3a4e14770"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["315e45a1d2a64a42871741f3a4e14770"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c76f193c4cb4fba99e64852a6ea46f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":550},
            "size":{
              "width":280,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5003f0f433bf4825b176b2a673fa8220",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":550},
                "size":{
                  "width":280,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b625191679e4caf91a481a7dc00d0ae",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":170,
              "y":500},
            "size":{
              "width":260,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19ea6c042bba4dec81e9817d98da7f80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":170,
                  "y":500},
                "size":{
                  "width":260,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68fe801b31b34357b8b0c55a69b95859",
          "label":"button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":266,
              "y":682},
            "size":{
              "width":104,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22739ebf4424448d9e8e2c385958685a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":266,
                  "y":682},
                "size":{
                  "width":104,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["68fe801b31b34357b8b0c55a69b95859"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["68fe801b31b34357b8b0c55a69b95859"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/销售单管理/button_u53.png",
            "selected~":"images/销售单管理/button_u53_selected.png",
            "mouseOver~":"images/销售单管理/button_u53_selected.png",
            "mouseDown~":"images/销售单管理/button_u53_mouseDown.png",
            "disabled~":"images/销售单管理/button_u53_disabled.png"}},
{
          "id":"5c64b5d44aed45ad83f395d22764c477",
          "label":"button label",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":270,
              "y":682},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a65289c25c4498693d8fbe435145999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":270,
                  "y":682},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["68fe801b31b34357b8b0c55a69b95859"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of button equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["68fe801b31b34357b8b0c55a69b95859"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d925059089d7407aa612fa9c86535ac3":{
      "packageId":"d925059089d7407aa612fa9c86535ac3",
      "type":"Axure:Master",
      "name":"Group",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bb956eace71741d39ff8d1d233d848a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":110,
                "y":19},
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"34e7f17d8003487ea75777fee257eebd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":110,
                    "y":19},
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/group/u1.png"}}]}}},
  "objectPaths":{
    "7b20563470664ef98577aec7bd2155e9":{
      "scriptId":"u0",
      "bb956eace71741d39ff8d1d233d848a6":{
        "scriptId":"u1"},
      "34e7f17d8003487ea75777fee257eebd":{
        "scriptId":"u2"}},
    "9c66b5f0d15b485cba56506cfd4f7f93":{
      "scriptId":"u3"},
    "34042213e26b434eafa9b1485b61a37f":{
      "scriptId":"u4"},
    "5492d37b90264b3581afbdfcdd8b49a1":{
      "scriptId":"u5"},
    "d5de589ff82346c1ac79b8dbc9915a06":{
      "scriptId":"u6"},
    "97a4943f5d224c5f90d49a62defc3d06":{
      "scriptId":"u7"},
    "f51c721fbd934143b7a92807191628bc":{
      "scriptId":"u8"},
    "e6890bb4a373486c805f3b7751385487":{
      "scriptId":"u9"},
    "d0483ab1930844ac9e26151a629ec506":{
      "scriptId":"u10"},
    "da73ca0465aa43c5ab910173213cba80":{
      "scriptId":"u11"},
    "e08f803eca4149488e1be53e099695e5":{
      "scriptId":"u12"},
    "071a15f3eb6445c09cd3d45dadd010c1":{
      "scriptId":"u13"},
    "62c4d7fbe91549d4b41e4f75cbb12644":{
      "scriptId":"u14"},
    "0430879f22474fc387b734bb9c814693":{
      "scriptId":"u15"},
    "f413b53cafd1472c899099fd56a6a85e":{
      "scriptId":"u16"},
    "1c9ff36143ee4cf69bacbf1729d573f5":{
      "scriptId":"u17"},
    "d7e82fe01e3c492b965071efed8e7029":{
      "scriptId":"u18"},
    "0eba0dbe7af24b7b927f6cb876c9ed42":{
      "scriptId":"u19"},
    "66d1773fc2a64909b55659fe6ca637f4":{
      "scriptId":"u20"},
    "5bc64df110db4dfca0e26c9336b4a3f3":{
      "scriptId":"u21"},
    "08f2702e4d764daa9d77a41c42c46feb":{
      "scriptId":"u22"},
    "7753204f9533438ab79d8326bce18a10":{
      "scriptId":"u23"},
    "c73ed1b6bfb245b888379335bfa108f6":{
      "scriptId":"u24"},
    "39e8171fa5a2417495d1233555cba15e":{
      "scriptId":"u25"},
    "5a30c1f8376e46b983c203e13d9cc19c":{
      "scriptId":"u26"},
    "2298954c4b8a4eebb5a05eeb7e4f9d2b":{
      "scriptId":"u27"},
    "52dc7bf74fec422299681336bcc56f2c":{
      "scriptId":"u28"},
    "314f3d8d4d204881990642cfca46cdfa":{
      "scriptId":"u29"},
    "7c760e10abbd4e81a590b7286f40ddb1":{
      "scriptId":"u30"},
    "8d3a1ea43ede4bfc9ffdc37ee6f09700":{
      "scriptId":"u31"},
    "cde21dbd3c8940e4a82c117649ce65ee":{
      "scriptId":"u32"},
    "2b16a62c169a4240aa9fc70911fa5432":{
      "scriptId":"u33"},
    "c92df91fc87c45639c4dca904a3a52e9":{
      "scriptId":"u34"},
    "f0c1bcea9859423cb512858d4225c680":{
      "scriptId":"u35"},
    "32544cdbafaf47e89896fd7b45e134fa":{
      "scriptId":"u36"},
    "b0b831aa3469473c92e5b333ff564a39":{
      "scriptId":"u37"},
    "e6a200a33e7d497f8dcece2615d65f60":{
      "scriptId":"u38"},
    "3cc748e0aff7474694b3d47089f1d225":{
      "scriptId":"u39"},
    "02f406a4931b4f2c94bce56c486f2256":{
      "scriptId":"u40"},
    "eaef942887f544998fffb280d16e004a":{
      "scriptId":"u41"},
    "0070613b3f7d48a284dfe5de4924a3a8":{
      "scriptId":"u42"},
    "fff1ecb4a2894cbab8d2eaa53b9e068c":{
      "scriptId":"u43"},
    "b1c0611e8b494855a0b242426c4d6eb7":{
      "scriptId":"u44"},
    "315e45a1d2a64a42871741f3a4e14770":{
      "scriptId":"u45"},
    "0b189fb362284fadaaa014372a5ebe6a":{
      "scriptId":"u46"},
    "f8924feb57c648028ff071bd75d0c4fa":{
      "scriptId":"u47"},
    "da9c9383e421418d9d208336b12a054e":{
      "scriptId":"u48"},
    "5c76f193c4cb4fba99e64852a6ea46f0":{
      "scriptId":"u49"},
    "5003f0f433bf4825b176b2a673fa8220":{
      "scriptId":"u50"},
    "9b625191679e4caf91a481a7dc00d0ae":{
      "scriptId":"u51"},
    "19ea6c042bba4dec81e9817d98da7f80":{
      "scriptId":"u52"},
    "68fe801b31b34357b8b0c55a69b95859":{
      "scriptId":"u53"},
    "22739ebf4424448d9e8e2c385958685a":{
      "scriptId":"u54"},
    "5c64b5d44aed45ad83f395d22764c477":{
      "scriptId":"u55"},
    "3a65289c25c4498693d8fbe435145999":{
      "scriptId":"u56"}}});