$axure.loadCurrentPage({
  "url":"favorlist.html",
  "generationDate":new Date(1423024882149.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"DroplistOption",
"ClickOnHandle"],
  "page":{
    "packageId":"a513783eaa804d6daf07d8d549e4fb56",
    "type":"Axure:Page",
    "name":"favorlist",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"16184dcc1c344fe49100ce1b949207d9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d925059089d7407aa612fa9c86535ac3"},
{
          "id":"50dac4c754fa4765bde1296b101c0259",
          "label":"tab",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":169,
              "y":149},
            "size":{
              "width":91,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"559d4a06c0ce4158a4db0d1a7f438a13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":169,
                  "y":149},
                "size":{
                  "width":91,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of tab equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["50dac4c754fa4765bde1296b101c0259"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/销售单管理/tab_u67.png",
            "selected~":"images/销售单管理/tab_u67_selected.png",
            "mouseDown~":"images/销售单管理/tab_u67_mouseDown.png",
            "disabled~":"images/销售单管理/tab_u67.png"}},
{
          "id":"b42e674ff8274f7b8ff4bec539a177dd",
          "label":"tab label",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":173,
              "y":153},
            "size":{
              "width":83,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8ffa144ee6451e89ddffdfa2915e18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":173,
                  "y":153},
                "size":{
                  "width":83,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of tab equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["50dac4c754fa4765bde1296b101c0259"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}},
{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to store",
                      "panelsToStates":[{
                          "panelPath":["d51201c6630345ad8dceb6c7be1833e2"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"bf9bf667e0b6462595c951cd4bd5c8a3",
          "label":"tab",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseDown":{
},
              "selected":{
},
              "disabled":{
}},
            "location":{
              "x":280,
              "y":150.5},
            "size":{
              "width":91,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084cb693c3c3408cb084f0dbc389c04f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseDown":{
},
                  "selected":{
},
                  "disabled":{
}},
                "location":{
                  "x":280,
                  "y":150.5},
                "size":{
                  "width":91,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of tab equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bf9bf667e0b6462595c951cd4bd5c8a3"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}},
{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to product",
                      "panelsToStates":[{
                          "panelPath":["d51201c6630345ad8dceb6c7be1833e2"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/销售单管理/tab_u67.png",
            "selected~":"images/销售单管理/tab_u67_selected.png",
            "mouseDown~":"images/销售单管理/tab_u67_mouseDown.png",
            "disabled~":"images/销售单管理/tab_u67.png"}},
{
          "id":"d51201c6630345ad8dceb6c7be1833e2",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":181},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"26c375f7cd8b4510a31eb6c26e4bff16",
              "label":"store",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c518e9c22de444b5946e83c515e538e4",
                  "label":"box, transparent",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "size":{
                      "width":290,
                      "height":499}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d3217b4502c840608bfe0f19b47be38f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "size":{
                          "width":290,
                          "height":499}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/box__transparent_u10.png"}},
{
                  "id":"ea6c7614692e4546a4db730bebc2cfae",
                  "label":"box",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":10},
                    "size":{
                      "width":110,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93aee74472b14044be66cc409d8ca0d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":10},
                        "size":{
                          "width":110,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/box_u12.png"}},
{
                  "id":"a9b2123971744bc8a113b1110b866d6c",
                  "label":"line, diagonal L-R",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":10},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de8a90a79c2c462681ec81d03f434725",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":10},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
                  "id":"6e208c9a6701467089e03286355e4645",
                  "label":"line, diagonal R-L",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":10},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e2c62eb5526f4f1b80619aaf3daf6be8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":10},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
                  "id":"e095df74bcf94aafbfccf1d522138068",
                  "label":"image placement label",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":39,
                      "y":49},
                    "size":{
                      "width":30,
                      "height":11},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"025f1958a9ef4a61bb1e45054660a06e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":39,
                          "y":49},
                        "size":{
                          "width":30,
                          "height":11},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/image_placement_label_u18.png"}},
{
                  "id":"c289145f813b443c90d6f4cc6d82f658",
                  "label":"text",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "verticalAlignment":"top",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":119,
                      "y":15},
                    "size":{
                      "width":141,
                      "height":35},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c120936aa21e4264983f9d6a0a990050",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "verticalAlignment":"top",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":119,
                          "y":15},
                        "size":{
                          "width":141,
                          "height":35},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"77ed64a9f6f343ea8f96c1705ed3303a",
                  "label":"box",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":110,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"95303296e02645eca23dc34f7e839711",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":120},
                        "size":{
                          "width":110,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/box_u12.png"}},
{
                  "id":"d08d6ad66b284f8ba282da8d5504b80d",
                  "label":"line, diagonal L-R",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1eb80842466a47e08109ec29a41c097b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":120},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
                  "id":"9a0b8535a79b4c518a85a628b88db824",
                  "label":"line, diagonal R-L",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4465cc2478574d97a4e31cdcb5335deb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":120},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
                  "id":"e6a676c4db174b7bbb50c0802aa53432",
                  "label":"image placement label",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":39,
                      "y":159},
                    "size":{
                      "width":30,
                      "height":11},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a7e5c851fdd45d58c358e1f3e9adc6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":39,
                          "y":159},
                        "size":{
                          "width":30,
                          "height":11},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/image_placement_label_u18.png"}},
{
                  "id":"c45f6b0b4e7443088dd7947dfa706b4f",
                  "label":"text",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "verticalAlignment":"top",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":119,
                      "y":125},
                    "size":{
                      "width":141,
                      "height":35},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12aca45f43de4c198854929a09330242",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "verticalAlignment":"top",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":119,
                          "y":125},
                        "size":{
                          "width":141,
                          "height":35},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"67e83fe2195c4a00bb7fa30ceff51060",
                  "label":"box",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":10,
                      "y":230},
                    "size":{
                      "width":110,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"390f498bb78e4f85b0d2baded66cf4f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":10,
                          "y":230},
                        "size":{
                          "width":110,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/box_u12.png"}},
{
                  "id":"07cd22e1e1d54a24abc9bb8d25aa3eb8",
                  "label":"line, diagonal L-R",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":10,
                      "y":230},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5e591fb789047c29c6961c2b7bb0920",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":10,
                          "y":230},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
                  "id":"1d1c32eeb66e41ddb6918d4f00f6ec17",
                  "label":"line, diagonal R-L",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":10,
                      "y":230},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f64583e8636402f9de9c9ba2c83eff8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":10,
                          "y":230},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
                  "id":"49a2bb1085b24393b3d175e7eb3f2869",
                  "label":"image placement label",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":49,
                      "y":269},
                    "size":{
                      "width":30,
                      "height":11},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"836f1176445447d0bf30eac7fd383472",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":49,
                          "y":269},
                        "size":{
                          "width":30,
                          "height":11},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/image_placement_label_u18.png"}},
{
                  "id":"dd38f2b2b1294a579441193cef51ff41",
                  "label":"text",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "verticalAlignment":"top",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":129,
                      "y":235},
                    "size":{
                      "width":141,
                      "height":35},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9da0710cbcd4fa2a1bc5614c3c28182",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "verticalAlignment":"top",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":129,
                          "y":235},
                        "size":{
                          "width":141,
                          "height":35},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"1032992db7ae427b9e6d73de8dacfd6f",
              "label":"product",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c186d5cc1e0c4cbeb9492cef533c3f81",
                  "label":"box, transparent",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "size":{
                      "width":290,
                      "height":499}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"344b3feb304b4fbcbd65637ba8dab9bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "size":{
                          "width":290,
                          "height":499}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/box__transparent_u10.png"}},
{
                  "id":"2c3e1d7f1da04018b723e4fc19b90500",
                  "label":"box",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":10},
                    "size":{
                      "width":110,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8761bfd560434280aa20f81086ee3ad1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":10},
                        "size":{
                          "width":110,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/box_u12.png"}},
{
                  "id":"d32faa5de5af4720a2e84d324b9efe08",
                  "label":"line, diagonal L-R",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":10},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef0a53d042694d458c32e8432eb6f0c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":10},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
                  "id":"75ea7cdf0c784a17befa785c82c26cc4",
                  "label":"line, diagonal R-L",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":10},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf15e81e74724db181ca7c8022d40742",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":10},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
                  "id":"bcfba2ef8bc24b0ba7f1fa22dc87bbed",
                  "label":"image placement label",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":39,
                      "y":49},
                    "size":{
                      "width":30,
                      "height":11},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e4274f879904ad7a86f2721c1c11303",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":39,
                          "y":49},
                        "size":{
                          "width":30,
                          "height":11},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/image_placement_label_u18.png"}},
{
                  "id":"40a4727f00484e7e898f3cd8da4883d0",
                  "label":"text",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "verticalAlignment":"top",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":119,
                      "y":15},
                    "size":{
                      "width":141,
                      "height":35},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7022df42e5394b23bdf0d5d5e1e4accd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "verticalAlignment":"top",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":119,
                          "y":15},
                        "size":{
                          "width":141,
                          "height":35},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a9d6d64803b54dc29034699e833572d1",
                  "label":"box",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":110,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"141e49673cdf4c569dc9e7486721cbb1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":120},
                        "size":{
                          "width":110,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/box_u12.png"}},
{
                  "id":"8682364a466d4028acb266dd747d8662",
                  "label":"line, diagonal L-R",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67d63e3e625840c0b3c26025bd3d31de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":120},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
                  "id":"0c597431c59c43f1ad076ff6e973bf72",
                  "label":"line, diagonal R-L",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19b52e1f1ebb4c0fb1ba387d387fc975",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":120},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
                  "id":"29dbcc657f4c4b19a1cdcee47a5dbcfa",
                  "label":"image placement label",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":39,
                      "y":159},
                    "size":{
                      "width":30,
                      "height":11},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c07c6c81ecf4948854d67c87ab4687b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":39,
                          "y":159},
                        "size":{
                          "width":30,
                          "height":11},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/image_placement_label_u18.png"}},
{
                  "id":"14317ff9e6914d35a299de717955a785",
                  "label":"text",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "verticalAlignment":"top",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":119,
                      "y":125},
                    "size":{
                      "width":141,
                      "height":35},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87e8643c520848b6be773f16d34f1862",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "verticalAlignment":"top",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":119,
                          "y":125},
                        "size":{
                          "width":141,
                          "height":35},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8ab6817a79a6408e8b4118e81a8fc6e6",
                  "label":"box",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":230},
                    "size":{
                      "width":110,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"afd466319ba14812827fef28cc2f005f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":230},
                        "size":{
                          "width":110,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/box_u12.png"}},
{
                  "id":"704433dbd26d43d1a2b844fe6c735243",
                  "label":"line, diagonal L-R",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":230},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"86c8a4025734480887f61174ac6baa50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":230},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_l-r_u11.png"}},
{
                  "id":"b36d97c0099548da93d77b5bba893c8e",
                  "label":"line, diagonal R-L",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":230},
                    "size":{
                      "width":109,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eadb7c6368f2491fa015041105f633bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":230},
                        "size":{
                          "width":109,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/group/line__diagonal_r-l_u13.png"}},
{
                  "id":"d6479467d0d2472ebac11348698a71b7",
                  "label":"image placement label",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":39,
                      "y":269},
                    "size":{
                      "width":30,
                      "height":11},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd6785f2e52d46d0be0706e38761b8cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":39,
                          "y":269},
                        "size":{
                          "width":30,
                          "height":11},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorlist/image_placement_label_u18.png"}},
{
                  "id":"62692bb41d384491a4c2d0c2120f30e9",
                  "label":"text",
                  "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "verticalAlignment":"top",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":119,
                      "y":235},
                    "size":{
                      "width":141,
                      "height":35},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c457b76db3c41c191c7ad688315b0ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d51201c6630345ad8dceb6c7be1833e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "verticalAlignment":"top",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":119,
                          "y":235},
                        "size":{
                          "width":141,
                          "height":35},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "d925059089d7407aa612fa9c86535ac3":{
      "packageId":"d925059089d7407aa612fa9c86535ac3",
      "type":"Axure:Master",
      "name":"Group",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bb956eace71741d39ff8d1d233d848a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":110,
                "y":19},
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"34e7f17d8003487ea75777fee257eebd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":110,
                    "y":19},
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/group/u1.png"}}]}}},
  "objectPaths":{
    "16184dcc1c344fe49100ce1b949207d9":{
      "scriptId":"u0",
      "bb956eace71741d39ff8d1d233d848a6":{
        "scriptId":"u1"},
      "34e7f17d8003487ea75777fee257eebd":{
        "scriptId":"u2"}},
    "50dac4c754fa4765bde1296b101c0259":{
      "scriptId":"u3"},
    "559d4a06c0ce4158a4db0d1a7f438a13":{
      "scriptId":"u4"},
    "b42e674ff8274f7b8ff4bec539a177dd":{
      "scriptId":"u5"},
    "6b8ffa144ee6451e89ddffdfa2915e18":{
      "scriptId":"u6"},
    "bf9bf667e0b6462595c951cd4bd5c8a3":{
      "scriptId":"u7"},
    "084cb693c3c3408cb084f0dbc389c04f":{
      "scriptId":"u8"},
    "d51201c6630345ad8dceb6c7be1833e2":{
      "scriptId":"u9"},
    "c518e9c22de444b5946e83c515e538e4":{
      "scriptId":"u10"},
    "d3217b4502c840608bfe0f19b47be38f":{
      "scriptId":"u11"},
    "ea6c7614692e4546a4db730bebc2cfae":{
      "scriptId":"u12"},
    "93aee74472b14044be66cc409d8ca0d1":{
      "scriptId":"u13"},
    "a9b2123971744bc8a113b1110b866d6c":{
      "scriptId":"u14"},
    "de8a90a79c2c462681ec81d03f434725":{
      "scriptId":"u15"},
    "6e208c9a6701467089e03286355e4645":{
      "scriptId":"u16"},
    "e2c62eb5526f4f1b80619aaf3daf6be8":{
      "scriptId":"u17"},
    "e095df74bcf94aafbfccf1d522138068":{
      "scriptId":"u18"},
    "025f1958a9ef4a61bb1e45054660a06e":{
      "scriptId":"u19"},
    "c289145f813b443c90d6f4cc6d82f658":{
      "scriptId":"u20"},
    "c120936aa21e4264983f9d6a0a990050":{
      "scriptId":"u21"},
    "77ed64a9f6f343ea8f96c1705ed3303a":{
      "scriptId":"u22"},
    "95303296e02645eca23dc34f7e839711":{
      "scriptId":"u23"},
    "d08d6ad66b284f8ba282da8d5504b80d":{
      "scriptId":"u24"},
    "1eb80842466a47e08109ec29a41c097b":{
      "scriptId":"u25"},
    "9a0b8535a79b4c518a85a628b88db824":{
      "scriptId":"u26"},
    "4465cc2478574d97a4e31cdcb5335deb":{
      "scriptId":"u27"},
    "e6a676c4db174b7bbb50c0802aa53432":{
      "scriptId":"u28"},
    "7a7e5c851fdd45d58c358e1f3e9adc6c":{
      "scriptId":"u29"},
    "c45f6b0b4e7443088dd7947dfa706b4f":{
      "scriptId":"u30"},
    "12aca45f43de4c198854929a09330242":{
      "scriptId":"u31"},
    "67e83fe2195c4a00bb7fa30ceff51060":{
      "scriptId":"u32"},
    "390f498bb78e4f85b0d2baded66cf4f5":{
      "scriptId":"u33"},
    "07cd22e1e1d54a24abc9bb8d25aa3eb8":{
      "scriptId":"u34"},
    "d5e591fb789047c29c6961c2b7bb0920":{
      "scriptId":"u35"},
    "1d1c32eeb66e41ddb6918d4f00f6ec17":{
      "scriptId":"u36"},
    "1f64583e8636402f9de9c9ba2c83eff8":{
      "scriptId":"u37"},
    "49a2bb1085b24393b3d175e7eb3f2869":{
      "scriptId":"u38"},
    "836f1176445447d0bf30eac7fd383472":{
      "scriptId":"u39"},
    "dd38f2b2b1294a579441193cef51ff41":{
      "scriptId":"u40"},
    "d9da0710cbcd4fa2a1bc5614c3c28182":{
      "scriptId":"u41"},
    "c186d5cc1e0c4cbeb9492cef533c3f81":{
      "scriptId":"u42"},
    "344b3feb304b4fbcbd65637ba8dab9bb":{
      "scriptId":"u43"},
    "2c3e1d7f1da04018b723e4fc19b90500":{
      "scriptId":"u44"},
    "8761bfd560434280aa20f81086ee3ad1":{
      "scriptId":"u45"},
    "d32faa5de5af4720a2e84d324b9efe08":{
      "scriptId":"u46"},
    "ef0a53d042694d458c32e8432eb6f0c2":{
      "scriptId":"u47"},
    "75ea7cdf0c784a17befa785c82c26cc4":{
      "scriptId":"u48"},
    "cf15e81e74724db181ca7c8022d40742":{
      "scriptId":"u49"},
    "bcfba2ef8bc24b0ba7f1fa22dc87bbed":{
      "scriptId":"u50"},
    "8e4274f879904ad7a86f2721c1c11303":{
      "scriptId":"u51"},
    "40a4727f00484e7e898f3cd8da4883d0":{
      "scriptId":"u52"},
    "7022df42e5394b23bdf0d5d5e1e4accd":{
      "scriptId":"u53"},
    "a9d6d64803b54dc29034699e833572d1":{
      "scriptId":"u54"},
    "141e49673cdf4c569dc9e7486721cbb1":{
      "scriptId":"u55"},
    "8682364a466d4028acb266dd747d8662":{
      "scriptId":"u56"},
    "67d63e3e625840c0b3c26025bd3d31de":{
      "scriptId":"u57"},
    "0c597431c59c43f1ad076ff6e973bf72":{
      "scriptId":"u58"},
    "19b52e1f1ebb4c0fb1ba387d387fc975":{
      "scriptId":"u59"},
    "29dbcc657f4c4b19a1cdcee47a5dbcfa":{
      "scriptId":"u60"},
    "2c07c6c81ecf4948854d67c87ab4687b":{
      "scriptId":"u61"},
    "14317ff9e6914d35a299de717955a785":{
      "scriptId":"u62"},
    "87e8643c520848b6be773f16d34f1862":{
      "scriptId":"u63"},
    "8ab6817a79a6408e8b4118e81a8fc6e6":{
      "scriptId":"u64"},
    "afd466319ba14812827fef28cc2f005f":{
      "scriptId":"u65"},
    "704433dbd26d43d1a2b844fe6c735243":{
      "scriptId":"u66"},
    "86c8a4025734480887f61174ac6baa50":{
      "scriptId":"u67"},
    "b36d97c0099548da93d77b5bba893c8e":{
      "scriptId":"u68"},
    "eadb7c6368f2491fa015041105f633bc":{
      "scriptId":"u69"},
    "d6479467d0d2472ebac11348698a71b7":{
      "scriptId":"u70"},
    "dd6785f2e52d46d0be0706e38761b8cd":{
      "scriptId":"u71"},
    "62692bb41d384491a4c2d0c2120f30e9":{
      "scriptId":"u72"},
    "3c457b76db3c41c191c7ad688315b0ce":{
      "scriptId":"u73"}}});