$axure.loadCurrentPage({
  "url":"oneyuancreateorder.html",
  "generationDate":new Date(1421046072985.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"DroplistOption",
"ClickOnHandle"],
  "page":{
    "packageId":"f0dbe59f1fd74cac87bd796f2c037dfc",
    "type":"Axure:Page",
    "name":"oneyuanCreateOrder",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8579468737ef4ef69703da05abd0edd8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d925059089d7407aa612fa9c86535ac3"},
{
          "id":"baa980e1bb1a47b6aedc4b4edf30e03b",
          "label":"box, transparent",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":148,
              "y":140},
            "size":{
              "width":304,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7444824bb21478c867b0c9318ea720d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":148,
                  "y":140},
                "size":{
                  "width":304,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/createorder/box__transparent_u9.png"}},
{
          "id":"311e07fc38304d6887a2baf5a0323128",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":158,
              "y":190},
            "size":{
              "width":172,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ee0cf117d14a2ebb42ffac139a4de6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":158,
                  "y":190},
                "size":{
                  "width":172,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3717fb3ad354b1fba370843e4e79d25",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":158,
              "y":150},
            "size":{
              "width":272,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b2c1471f71459e9a356b4ebd0049b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":158,
                  "y":150},
                "size":{
                  "width":272,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a6092d753024f1cb579ce8489ffab08",
          "label":"box, transparent",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":153,
              "y":350},
            "size":{
              "width":297,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac0c6893db4e46419fd7d67e6990dc28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":153,
                  "y":350},
                "size":{
                  "width":297,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/createorder/box__transparent_u47.png"}},
{
          "id":"64cd0dd719f44fafbd7ef9b1c46ddcc8",
          "label":"button label",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":186,
              "y":370},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d64a537af44fa48d11d32b887fab01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":186,
                  "y":370},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of Unidentified equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of Unidentified equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6e280dc2503428b9b059f13575c3fb4",
          "label":"button label",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":302,
              "y":370},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"177308283da54872ab45eccd688f415e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":302,
                  "y":370},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of Unidentified equal to &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of Unidentified equal to &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d925059089d7407aa612fa9c86535ac3":{
      "packageId":"d925059089d7407aa612fa9c86535ac3",
      "type":"Axure:Master",
      "name":"Group",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bb956eace71741d39ff8d1d233d848a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":110,
                "y":19},
              "size":{
                "width":380,
                "height":800},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"34e7f17d8003487ea75777fee257eebd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":110,
                    "y":19},
                  "size":{
                    "width":380,
                    "height":800},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/group/u1.png"}}]}}},
  "objectPaths":{
    "8579468737ef4ef69703da05abd0edd8":{
      "scriptId":"u0",
      "bb956eace71741d39ff8d1d233d848a6":{
        "scriptId":"u1"},
      "34e7f17d8003487ea75777fee257eebd":{
        "scriptId":"u2"}},
    "baa980e1bb1a47b6aedc4b4edf30e03b":{
      "scriptId":"u3"},
    "b7444824bb21478c867b0c9318ea720d":{
      "scriptId":"u4"},
    "311e07fc38304d6887a2baf5a0323128":{
      "scriptId":"u5"},
    "37ee0cf117d14a2ebb42ffac139a4de6":{
      "scriptId":"u6"},
    "d3717fb3ad354b1fba370843e4e79d25":{
      "scriptId":"u7"},
    "a6b2c1471f71459e9a356b4ebd0049b4":{
      "scriptId":"u8"},
    "3a6092d753024f1cb579ce8489ffab08":{
      "scriptId":"u9"},
    "ac0c6893db4e46419fd7d67e6990dc28":{
      "scriptId":"u10"},
    "64cd0dd719f44fafbd7ef9b1c46ddcc8":{
      "scriptId":"u11"},
    "22d64a537af44fa48d11d32b887fab01":{
      "scriptId":"u12"},
    "e6e280dc2503428b9b059f13575c3fb4":{
      "scriptId":"u13"},
    "177308283da54872ab45eccd688f415e":{
      "scriptId":"u14"}}});